server {
    listen 8080;

    location = /_auth {
        internal;
        proxy_pass http://users:8000/auth;
        proxy_pass_request_body off;
	proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }

    location /docs/ {
        proxy_pass http://swagger_ui:8080/;
    }

    location = /users/customers/create {
        proxy_pass http://users:8000/customers/create;
    }

    location = /users/openapi.json {
        proxy_pass http://users:8000/openapi.json;
    }

    location /users/ {
        auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://users:8000/;
    }

    location = /inventory/openapi.json {
        proxy_pass http://inventory:8000/openapi.json;
    }

    location /inventory/ {
	auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://inventory:8000/;
    }

    location = /orders/openapi.json {
        proxy_pass http://orders:8000/openapi.json;
    }

    location /orders/ {
	auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://orders:8000/;
    }

    location = /notifications/openapi.json {
        proxy_pass http://notifications:8000/openapi.json;
    }

    location /notifications/ {
	auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://notifications:8000/;
    }
}

