server {
    listen 8080;

    location = /_auth {
        internal;
        proxy_pass http://customers:8000/auth/validate;
        proxy_pass_request_body off;
	proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }

    location = /customers/create {
        proxy_pass http://customers:8000/customers/create;
    }

    location /customers {
        auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://customers:8000/customers;
    }

    location /admins {
        auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://customers:8000/admins;
    }

    location /products {
        auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://inventory:8001/products;
    }

    location /categories {
        auth_request /_auth;
        auth_request_set $customer_id $upstream_http_x_customer_id;
        auth_request_set $is_admin $upstream_http_x_is_admin;
        proxy_set_header x-customer-id $customer_id;
        proxy_set_header x-is-admin $is_admin;

        proxy_pass http://inventory:8001/categories;
    }
}

