services:
  api_gateway:
    image: docker.io/library/nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - customers
      - inventory
      - orders

  customers_db:
    image: docker.io/library/postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customers_db
    healthcheck:
      test: "pg_isready -h customers_db"
      interval: 1s
      timeout: 5s
      retries: 10

  customers:
    build: ../customers
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@customers_db:5432/customers_db
    depends_on:
      customers_db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ../customers/src
          target: /customers/src

  inventory_db:
    image: docker.io/library/postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    healthcheck:
      test: "pg_isready -h inventory_db"
      interval: 1s
      timeout: 5s
      retries: 10

  inventory:
    build: ../inventory
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@inventory_db:5432/inventory_db
    depends_on:
      inventory_db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ../inventory/src
          target: /inventory/src

  orders_db:
    image: docker.io/library/postgres:17-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    healthcheck:
      test: "pg_isready -h orders_db"
      interval: 1s
      timeout: 5s
      retries: 10

  orders:
    build: ../orders
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@orders_db:5432/orders_db
      INVENTORY_BASE_URL: http://inventory:8000
    depends_on:
      orders_db:
        condition: service_healthy
      inventory:
        condition: service_started

    develop:
      watch:
        - action: sync
          path: ../orders/src
          target: /orders/src

